#路由网关端口号，所有的微服务都访问路由网关的端口
server:
  port: 20000
spring:
  application:
    name: gateway
    #根据路径对应每个微服务
  cloud:
    consul:
      discovery:
        service-name: gateway
    gateway:
      routes:
        #user
        - id: user
          uri: lb://web-user
          predicates:
            - Path=/sso/**

        #admin
        - id: admin
          uri: lb://web-admin
          predicates:
            - Path=/**